- name: Install html-xml-utils
  package:
    name: "{{ item }}"
    state: present
  loop:
    - html-xml-utils
    - glow
  tags:
    - ansible-examples
    - ae

- name: Create install path
  become: false
  file:
    path: "{{ ae_install_path }}"
    state: directory
  tags:
    - ansible-examples
    - ae

- name: Copy ansible examples script
  become: false
  template:
    src: ae.sh.j2
    dest: "{{ ae_install_path }}/ae.sh"
    mode: "0750"
  tags:
    - ansible-examples
    - ae

- name: Copy html2md
  become: false
  copy:
    src: html2md
    dest: "{{ ae_install_path }}/html2md"
    mode: "0750"
  tags:
    - ansible-examples
    - ae

- name: Add alias in ~/.bashrc
  become: false
  blockinfile:
    path: ~/.bashrc
    block: |
      alias ae="{{ ae_install_path }}/ae.sh"
  tags:
    - ansible-examples
    - ae
